Controllers/ChefController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Recipes.Data;
using Recipes.Models;


namespace Recipes.Controllers
{
    [Authorize]
    public class ChefController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public ChefController(ApplicationDbContext context, IWebHostEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }

       

        // GET: Chef
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Chef.Include(c => c.Gender).Include(c => c.WorldCuisines);
            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> FamousChefs()
        {
            var famousChefs = await _context.Chef.ToListAsync();
            return View(famousChefs);
        }

        public async Task<IActionResult> Info(int id)
        {
            var db = from chef in _context.Chef where chef.Id == id select chef;
            return View(await db.Include(c => c.WorldCuisines).FirstOrDefaultAsync());
        }

        // GET: Chef/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chef = await _context.Chef
                .Include(c => c.Gender)
                .Include(c => c.WorldCuisines)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (chef == null)
            {
                return NotFound();
            }

            return View(chef);
        }

        // GET: Chef/Create
        public IActionResult Create()
        {
            ViewData["GenderId"] = new SelectList(_context.Gender, "Id", "GenderName");
            ViewData["WorldCuisinesId"] = new SelectList(_context.WorldCuisines, "Id", "Name");
            return View();
        }

        // POST: Chef/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Birth,Image,Information,GenderId,WorldCuisinesId")] Chef chef)
        {
            if (ModelState.IsValid)
            {
                string webRootPath = _hostingEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;


                string fileName = Guid.NewGuid().ToString();
                var uploads = Path.Combine(webRootPath, @"images\chef");
                var extension = Path.GetExtension(files[0].FileName);

                using (var fileStream = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                {
                    files[0].CopyTo(fileStream);
                }
                chef.Image = @"\images\chef\" + fileName + extension;
                _context.Add(chef);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GenderId"] = new SelectList(_context.Gender, "Id", "GenderName", chef.GenderId);
            ViewData["WorldCuisinesId"] = new SelectList(_context.WorldCuisines, "Id", "Name", chef.WorldCuisinesId);
            return View(chef);
        }

        // GET: Chef/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chef = await _context.Chef.FindAsync(id);
            if (chef == null)
            {
                return NotFound();
            }
            ViewData["GenderId"] = new SelectList(_context.Gender, "Id", "GenderName", chef.GenderId);
            ViewData["WorldCuisinesId"] = new SelectList(_context.WorldCuisines, "Id", "Name", chef.WorldCuisinesId);
            return View(chef);
        }

        // POST: Chef/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Birth,Image,Information,GenderId,WorldCuisinesId")] Chef chef)
        {
            if (id != chef.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(chef);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ChefExists(chef.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GenderId"] = new SelectList(_context.Gender, "Id", "GenderName", chef.GenderId);
            ViewData["WorldCuisinesId"] = new SelectList(_context.WorldCuisines, "Id", "Name", chef.WorldCuisinesId);
            return View(chef);
        }

        // GET: Chef/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chef = await _context.Chef
                .Include(c => c.Gender)
                .Include(c => c.WorldCuisines)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (chef == null)
            {
                return NotFound();
            }

            return View(chef);
        }

        // POST: Chef/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var chef = await _context.Chef.FindAsync(id);
            _context.Chef.Remove(chef);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ChefExists(int id)
        {
            return _context.Chef.Any(e => e.Id == id);
        }
    }
}

Controllers/FoodsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Recipes.Data;
using Recipes.Models;

namespace Recipes.Controllers
{
    [Authorize]
    public class FoodsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public FoodsController(ApplicationDbContext context, IWebHostEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }
        // GET: Food
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Food.Include(f => f.Category).Include(f => f.Language).Include(f => f.Region);
            return View(await applicationDbContext.ToListAsync());
        }

        public IActionResult Food(int id)
        {
            var food = _context.Food.FirstOrDefault(f => f.Id == id);

            return View(food);
        }

        // GET: Food/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var food = await _context.Food
                .Include(f => f.Category)
                .Include(f => f.Language)
                .Include(f => f.Region)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (food == null)
            {
                return NotFound();
            }

            return View(food);
        }

        // GET: Food/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Catergory, "Id", "CategoryName");
            ViewData["LanguageId"] = new SelectList(_context.Language, "Id", "LanguageName");
            ViewData["RegionId"] = new SelectList(_context.Region, "Id", "RegionName");
            return View();
        }

        // POST: Food/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FoodName,Materials,Recipe,Banner,Score,CategoryId,LanguageId,RegionId")] Food food)
        {
            if (ModelState.IsValid)
            {
                string webRootPath = _hostingEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;


                string fileName = Guid.NewGuid().ToString();
                var uploads = Path.Combine(webRootPath, @"images\food");
                var extension = Path.GetExtension(files[0].FileName);

                using (var fileStream = new FileStream(Path.Combine(uploads, fileName + extension), FileMode.Create))
                {
                    files[0].CopyTo(fileStream);
                }
                food.Banner = @"\images\food\" + fileName + extension;
                _context.Add(food);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Catergory, "Id", "CategoryName", food.CategoryId);
            ViewData["LanguageId"] = new SelectList(_context.Language, "Id", "LanguageName", food.LanguageId);
            ViewData["RegionId"] = new SelectList(_context.Region, "Id", "RegionName", food.RegionId);
            return View(food);
        }

        // GET: Food/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var food = await _context.Food.FindAsync(id);
            if (food == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Catergory, "Id", "Id", food.CategoryId);
            ViewData["LanguageId"] = new SelectList(_context.Language, "Id", "Id", food.LanguageId);
            ViewData["RegionId"] = new SelectList(_context.Region, "Id", "Id", food.RegionId);
            return View(food);
        }

        // POST: Food/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FoodName,Materials,Recipe,Banner,Score,CategoryId,LanguageId,RegionId")] Food food)
        {
            if (id != food.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(food);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FoodExists(food.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Catergory, "Id", "Id", food.CategoryId);
            ViewData["LanguageId"] = new SelectList(_context.Language, "Id", "Id", food.LanguageId);
            ViewData["RegionId"] = new SelectList(_context.Region, "Id", "Id", food.RegionId);
            return View(food);
        }

        // GET: Food/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var food = await _context.Food
                .Include(f => f.Category)
                .Include(f => f.Language)
                .Include(f => f.Region)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (food == null)
            {
                return NotFound();
            }

            return View(food);
        }

        // POST: Food/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var food = await _context.Food.FindAsync(id);
            _context.Food.Remove(food);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FoodExists(int id)
        {
            return _context.Food.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Recipes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/modern-business.css" rel="stylesheet">
</head>
<body>
    <header>
        @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Recipes</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav> *@
        <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-warning fixed-top">
            <div class="container">
                <a class="navbar-brand " asp-area="" asp-controller="Home" asp-action="Index">
                    <img class="brand" src="~/images/icon.png" alt="Logo" style="width:30px">
                </a>
                <a class="navbar-brand" style="color: #159929;font-family:'Segoe Script';font-weight:900" href="/">Keşke-K</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarResponsive">
                    @* <form class="form-inline my-2 my-lg-0">
                            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-light my-2 my-sm-0" style="color:black" type="submit">Search</button>
                        </form>*@
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a href="?culture=en-US" class="nav-link">English</a>
                        </li>
                        <li class="nav-item">
                            <a href="?culture=tr-TR" class="nav-link">Turkish</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/">@Localizer["home"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/chef/famousChefs">@Localizer["famousChefs"]</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                @Localizer["regions"]
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
                                <a class="dropdown-item" href="/region/foods/1">@Localizer["marmara"]</a>
                                <a class="dropdown-item" href="/region/foods/2">@Localizer["karadeniz"]</a>
                                <a class="dropdown-item" href="/region/foods/3">@Localizer["ege"]</a>
                                <a class="dropdown-item" href="/region/foods/4">@Localizer["akdeniz"]</a>
                                <a class="dropdown-item" href="/region/foods/5">@Localizer["anadolu"]</a>
                                <a class="dropdown-item" href="/region/foods/6">@Localizer["dogu"]</a>
                                <a class="dropdown-item" href="/region/foods/7">@Localizer["guneydogu"]</a>
                            </div>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    @Localizer["admin"]
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">
                                    <a class="dropdown-item" asp-area="" asp-controller="Language" asp-action="Index">@Localizer["languages"]</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Category" asp-action="Index">@Localizer["categories"]</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Region" asp-action="Index">@Localizer["admin-regions"]</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Gender" asp-action="Index">@Localizer["genders"]</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="WorldCuisines" asp-action="Index">@Localizer["worldcusines"]</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Chef" asp-action="Index">@Localizer["admin-chefs"]</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Foods" asp-action="Index">@Localizer["admin-foods"]</a>
                                </div>
                            </li>
                        }

                    </ul>
                    @* <form>
                            <button class="btn btn-outline-light my-2 my-sm-0" style="color:black" type="submit">Sign in</button>
                        </form> *@

                    <div>

                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                                aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                            <partial name="_LoginPartial" />
                            <ul class="navbar-nav flex-grow-1">
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top bg-warning footer text-muted">
        <div class="container">
            <h5>@Localizer["contact"]</h5>
            &copy; 2020 - Recipes
            <a href="mailto:elifsezer724@gmail.com">Elif Sezer</a>
            <a href="mailto:serapgulgen05@gmail.com">Serap Gülgen</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>